relativeURLS=true
languageCode = "en-us"
title = "David Macías"
googleAnalytics = "UA-49528577-2"
theme = "beautifulhugo"
Paginate = 10
disqusShortname = "coudingjournal"

[params]
  twitterName = "davidmacias"
  githubName = "davidmacias"
  subtitle = "Adventures in the world of Java, Spring and Angular"  
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  blogTitle = "Coding Journal"

[Author]
  name = "davidmacias"
  email = "david_4_1_4@hotmail.com"
  github = "davidmacias"
  twitter = "davidmacias"  

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2          

[[menu.main]]
    name = "About me / contact"
    url = "/about/"
    weight = 3      